# Taskfile
version: '3'

env:
  ENV: '{{.ENV | default "test"}}'

dotenv: ['common.env', '{{.ENV}}.env']

tasks:
  default:
    cmds:
      - echo "ENV '{{.ENV}}', endpoint '$ENDPOINT'"
    silent: true

  conditional:
    cmds:
      - if [ "{{.ENV}}" = "prod" ]; then echo "Running conditionally"; else echo "Skipping in ENV '{{.ENV}}'"; fi
    silent: true