# Taskfile
version: '3'

env:
  ENV: '{{.ENV | default "test"}}'

dotenv: ['common.env', '{{.ENV}}.env']

tasks:
  default:
    cmds:
      - echo "ENV '{{.ENV}}', endpoint '$ENDPOINT'"
    silent: true

  test:
    cmds:
      - bats **/*.bats
