name: CI
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: donaldm314/ubuntu-bats:101
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: "Test task with bats"
        run: |
          bats --version
          ./bats.sh
